export const towers = [
  {
    name: 'card.tower1.name',
    description: 'card.tower1.description',
    photo: '/towers-photo/staromestska.jpg',
    price: 170,
    constructionCentury: 'card.tower1.constructionCentury',
    location: 'location.oldTown',
  },
  {
    name: 'card.tower2.name',
    description: 'card.tower2.description',
    photo: '/towers-photo/klementinum.jpg',
    price: 300,
    constructionCentury: 'card.tower2.constructionCentury',
    location: 'location.oldTown',
  },
  {
    name: 'card.tower3.name',
    description: 'card.tower3.description',
    photo: '/towers-photo/malostr-most.jpg',
    price: 190,
    constructionCentury: 'card.tower3.constructionCentury',
    location: 'location.smallTown',
  },
  {
    name: 'card.tower4.name',
    description: 'card.tower4.description',
    photo: '/towers-photo/svatomikulas.jpg',
    price: 190,
    constructionCentury: 'card.tower4.constructionCentury',
    location: 'location.smallTown',
  },
  {
    name: 'card.tower5.name',
    description: 'card.tower5.description',
    photo: '/towers-photo/st-vitus-cathedral.jpg',
    price: 150,
    constructionCentury: 'card.tower5.constructionCentury',
    location: 'location.oldTown',
  },
  {
    name: 'card.tower6.name',
    description: 'card.tower6.description',
    photo: '/towers-photo/novomlynska.jpg',
    price: 150,
    constructionCentury: 'card.tower6.constructionCentury',
    location: 'location.newTown',
  },
  {
    name: 'card.tower7.name',
    description: 'card.tower7.description',
    photo: '/towers-photo/prasna-brana.jpg',
    price: 190,
    constructionCentury: 'card.tower7.constructionCentury',
    location: 'location.oldTown',
  },
  {
    name: 'card.tower8.name',
    description: 'card.tower8.description',
    photo: '/towers-photo/staromestska-radnice.jpg',
    price: 390,
    constructionCentury: 'card.tower8.constructionCentury',
    location: 'location.oldTown',
  },
  {
    name: 'card.tower9.name',
    description: 'card.tower9.description',
    photo: '/towers-photo/petrzin.jpg',
    price: 220,
    constructionCentury: 'card.tower9.constructionCentury',
    location: 'location.smallTown',
  },
  {
    name: 'card.tower10.name',
    description: 'card.tower10.description',
    photo: '/towers-photo/zizkovska.jpg',
    price: 250,
    constructionCentury: 'card.tower10.constructionCentury',
    location: 'location.zizkov',
  },
];
