export const towers = [
  {
    id: 1,
    name: 'card.tower1.name',
    description: 'card.tower1.description',
    photo: '/towers-photo/staromestska.jpg',
    price: 170,
    constructionCentury: 'card.tower1.constructionCentury',
    location: 'location.oldTown',
    height: 47,
    century: 14,
    galleryItems: [
      '/towers-photo/staromestska1.jpg',
      '/towers-photo/staromestska2.jpg',
      '/towers-photo/staromestska3.jpg',
    ],
    bigdescription: 'card.tower1.bigdescription',
    subtitle1: 'card.tower1.subtitle1',
    subtitle2: 'card.tower1.subtitle2',
    subtitle3: 'card.tower1.subtitle3',
    subtitle4: 'card.tower1.subtitle4',
    urlTicket:
      'https://www.prague.eu/cs/objekt/mista/197/staromestska-mostecka-vez',
    placeId: 'ChIJMbJV6eWUC0cRZM00zzxyBhA',
    urlPlace:
      'https://www.google.com/maps/place/Old+Town+Bridge+Tower/@50.0862306,14.4110392,17z/data=!3m1!4b1!4m6!3m5!1s0x470b94e5e955b231:0x1006723ccf34cd64!8m2!3d50.0862306!4d14.4136141!16s%2Fg%2F1234n3hk?entry=ttu',
    operation: [
      [1, 3, 1, 7, '10:00-18:00'],
      [4, 5, 1, 7, '10:00-19:00'],
      [6, 8, 1, 7, '09:00-21:00'],
      [9, null, 1, 7, '10:00-19:00'],
      [10, 11, 1, 7, '10:00-18:00'],
      [12, null, 1, 7, '10:00-20:00'],
    ],
  },
  {
    id: 2,
    name: 'card.tower2.name',
    description: 'card.tower2.description',
    photo: '/towers-photo/klementinum.jpg',
    price: 270,
    constructionCentury: 'card.tower2.constructionCentury',
    location: 'location.oldTown',
    height: 68,
    century: 18,
    galleryItems: [
      '/towers-photo/klementinum1.jpg',
      '/towers-photo/klementinum2.jpg',
      '/towers-photo/klementinum3.jpeg',
    ],
    bigdescription: 'card.tower2.bigdescription',
    subtitle1: 'card.tower2.subtitle1',
    subtitle2: 'card.tower2.subtitle2',
    subtitle3: 'card.tower2.subtitle3',
    subtitle4: 'card.tower2.subtitle4',
    urlTicket:
      'https://www.prague.eu/cs/objekt/mista/4071/astronomicka-vez-a-barokni-knihovna-klementinum#colosseumTickets',
    placeId: 'ChIJNUIyNe-UC0cRnw1-EJKuNLI',
    operation: [[4, 9, 1, 7, '09:00-21:00']],
  },
  {
    id: 3,
    name: 'card.tower3.name',
    description: 'card.tower3.description',
    photo: '/towers-photo/malostr-most.jpg',
    price: 190,
    constructionCentury: 'card.tower3.constructionCentury',
    location: 'location.lesserTown',
    height: 43.5,
    century: 12,
    galleryItems: [
      '/towers-photo/malostranska1.jpg',
      '/towers-photo/malostranska2.jpg',
      '/towers-photo/malostranska3.jpeg',
    ],
    bigdescription: 'card.tower3.bigdescription',
    subtitle1: 'card.tower3.subtitle1',
    subtitle2: 'card.tower3.subtitle2',
    subtitle3: 'card.tower3.subtitle3',
    subtitle4: 'card.tower3.subtitle4',
    urlTicket:
      'https://www.prague.eu/cs/objekt/mista/204/malostranske-mostecke-veze',
    placeId: 'ChIJ7V007-OUC0cRCCh69m3Lnuw',
    operation: [
      [1, 3, 1, 7, '10:00-18:00'],
      [4, 5, 1, 7, '10:00-19:00'],
      [6, 8, 1, 7, '09:00-21:00'],
      [9, null, 1, 7, '10:00-19:00'],
      [10, 11, 1, 7, '10:00-18:00'],
      [12, null, 1, 7, '10:00-20:00'],
    ],
  },
  {
    id: 4,
    name: 'card.tower4.name',
    description: 'card.tower4.description',
    photo: '/towers-photo/svatomikulas.jpg',
    price: 190,
    constructionCentury: 'card.tower4.constructionCentury',
    location: 'location.lesserTown',
    height: 65,
    century: 18,
    galleryItems: [
      '/towers-photo/svatomikulas1.jpg',
      '/towers-photo/svatomikulas2.jpg',
      '/towers-photo/svatomikulas3.jpg',
    ],
    bigdescription: 'card.tower4.bigdescription',
    subtitle1: 'card.tower4.subtitle1',
    subtitle2: 'card.tower4.subtitle2',
    subtitle3: 'card.tower4.subtitle3',
    subtitle4: 'card.tower4.subtitle4',
    urlTicket:
      'https://www.prague.eu/cs/objekt/mista/175/svatomikulasska-mestska-zvonice',
    placeId: 'ChIJ2xLlJOKUC0cRhuLwovjdffk',
    operation: [
      [1, 3, 1, 7, '10:00-18:00'],
      [4, 5, 1, 7, '10:00-19:00'],
      [6, 8, 1, 7, '09:00-21:00'],
      [9, null, 1, 7, '10:00-19:00'],
      [10, 11, 1, 7, '10:00-18:00'],
      [12, null, 1, 7, '10:00-20:00'],
    ],
  },
  {
    id: 5,
    name: 'card.tower5.name',
    description: 'card.tower5.description',
    photo: '/towers-photo/st-vitus-cathedral.jpg',
    price: 150,
    constructionCentury: 'card.tower5.constructionCentury',
    location: 'location.oldTown',
    height: 96.6,
    century: 14,
    galleryItems: [
      '/towers-photo/st-vitus-cathedral1.jpeg',
      '/towers-photo/st-vitus-cathedral2.jpg',
      '/towers-photo/st-vitus-cathedral3.jpeg',
    ],
    bigdescription: 'card.tower5.bigdescription',
    subtitle1: 'card.tower5.subtitle1',
    subtitle2: 'card.tower5.subtitle2',
    subtitle3: 'card.tower5.subtitle3',
    subtitle4: 'card.tower5.subtitle4',
    urlTicket:
      'https://www.katedralasvatehovita.cz/cs/prakticke-informace/jizni-vez-katedraly',
    placeId: 'ChIJW08COB6VC0cRoonZ8lA4rWk',
    operation: [
      [4, 10, 1, 7, '10:00-18:00'],
      [11, 3, 1, 7, '10:00-17:00'],
    ],
  },
  {
    id: 6,
    name: 'card.tower6.name',
    description: 'card.tower6.description',
    photo: '/towers-photo/novomlynska.jpg',
    price: 135,
    constructionCentury: 'card.tower6.constructionCentury',
    location: 'location.newTown',
    height: 42,
    century: 17,
    galleryItems: [
      '/towers-photo/novomlynska1.jpg',
      '/towers-photo/novomlynska2.jpeg',
      '/towers-photo/novomlynska3.jpg',
    ],
    bigdescription: 'card.tower6.bigdescription',
    subtitle1: 'card.tower6.subtitle1',
    subtitle2: 'card.tower6.subtitle2',
    subtitle3: 'card.tower6.subtitle3',
    subtitle4: 'card.tower6.subtitle4',
    urlTicket:
      'https://www.prague.eu/cs/objekt/mista/2858/novomlynska-vodarenska-vez',
    placeId: 'ChIJ745_usGUC0cRkulIKiAzTQ4',
    operation: [
      [4, 9, 1, 7, '10:00-18:00'],
      [10, 12, 5, 7, '10:00-18:00'],
    ],
  },
  {
    id: 7,
    name: 'card.tower7.name',
    description: 'card.tower7.description',
    photo: '/towers-photo/prasna-brana.jpg',
    price: 190,
    constructionCentury: 'card.tower7.constructionCentury',
    location: 'location.oldTown',
    height: 65,
    century: 15,
    galleryItems: [
      '/towers-photo/prasna-brana1.jpg',
      '/towers-photo/prasna-brana2.jpg',
      '/towers-photo/prasna-brana3.jpg',
    ],
    bigdescription: 'card.tower7.bigdescription',
    subtitle1: 'card.tower7.subtitle1',
    subtitle2: 'card.tower7.subtitle2',
    subtitle3: 'card.tower7.subtitle3',
    subtitle4: 'card.tower7.subtitle4',
    urlTicket: 'https://www.prague.eu/cs/objekt/mista/102/prasna-brana',
    placeId: 'ChIJBfIPBeuUC0cRphNG7F-4SZM',
    operation: [
      [1, 3, 1, 7, '10:00-18:00'],
      [4, 5, 1, 7, '10:00-19:00'],
      [6, 8, 1, 7, '09:00-21:00'],
      [9, null, 1, 7, '10:00-19:00'],
      [10, 11, 1, 7, '10:00-18:00'],
      [12, null, 1, 7, '10:00-20:00'],
    ],
  },

  {
    id: 8,
    name: 'card.tower8.name',
    description: 'card.tower8.description',
    photo: '/towers-photo/staromestska-radnice.jpg',
    price: 390,
    constructionCentury: 'card.tower8.constructionCentury',
    location: 'location.oldTown',
    height: 69.5,
    century: 14,
    galleryItems: [
      '/towers-photo/staromestska-radnice1.jpg',
      '/towers-photo/staromestska-radnice2.jpg',
      '/towers-photo/staromestska-radnice3.jpg',
    ],
    bigdescription: 'card.tower8.bigdescription',
    subtitle1: 'card.tower8.subtitle1',
    subtitle2: 'card.tower8.subtitle2',
    subtitle3: 'card.tower8.subtitle3',
    subtitle4: 'card.tower8.subtitle4',
    urlTicket:
      'https://www.prague.eu/cs/objekt/mista/3126/vez-staromestske-radnice',
    placeId: 'ChIJVTa4MOmUC0cR1WjVAxfAAws',
    operation: [
      [1, 3, 1, null, '11:00-20:00'],
      [null, null, 2, 7, '10:00-20:00'],
      [4, 12, 1, null, '11:00-21:00'],
      [null, null, 2, 7, '09:00-21:00'],
    ],
  },
  {
    id: 9,
    name: 'card.tower9.name',
    description: 'card.tower9.description',
    photo: '/towers-photo/petrzin.jpg',
    price: 290,
    constructionCentury: 'card.tower9.constructionCentury',
    location: 'location.lesserTown',
    height: 58.7,
    century: 19,
    galleryItems: [
      '/towers-photo/petrzin1.jpg',
      '/towers-photo/petrzin2.jpg',
      '/towers-photo/petrzin3.jpg',
    ],
    bigdescription: 'card.tower9.bigdescription',
    subtitle1: 'card.tower9.subtitle1',
    subtitle2: 'card.tower9.subtitle2',
    subtitle3: 'card.tower9.subtitle3',
    subtitle4: 'card.tower9.subtitle4',
    urlTicket: 'https://www.prague.eu/cs/objekt/mista/116/petrinska-rozhledna',
    placeId: 'ChIJd71LDf2UC0cRkcGvwf8x33E',
    operation: [
      [1, 3, 1, 7, '10:00-18:00'],
      [4, 5, 1, 7, '09:00-20:00'],
      [6, 9, 1, 7, '09:00-21:00'],
      [10, 12, 1, 7, '10:00-20:00'],
    ],
  },
  {
    id: 10,
    name: 'card.tower10.name',
    description: 'card.tower10.description',
    photo: '/towers-photo/zizkovska.jpg',
    price: 250,
    constructionCentury: 'card.tower10.constructionCentury',
    location: 'location.zizkov',
    height: 216,
    century: 20,
    galleryItems: [
      '/towers-photo/zizkovska1.jpg',
      '/towers-photo/zizkovska2.jpg',
      '/towers-photo/zizkovska3.jpg',
    ],
    bigdescription: 'card.tower10.bigdescription',
    subtitle1: 'card.tower10.subtitle1',
    subtitle2: 'card.tower10.subtitle2',
    subtitle3: 'card.tower10.subtitle3',
    subtitle4: 'card.tower10.subtitle4',
    urlTicket:
      'https://towerpark.cz/produkt/elektronicka-vstupenka-do-observatore/',
    placeId: 'ChIJweACSJyUC0cRE4gGU06KHKY',
    operation: [[1, 12, 1, 7, '09:00-24:00']],
  },
];
